services:
  api:
    build:
      context: ./api
    ports:
      - "3001:3001"
    networks:
      - clima-bot

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - clima-bot

networks:
  clima-bot:
    driver: bridge
