services:
  api:
    build:
      context: ./api
    ports:
      - "3001:3001"
    networks:
      - clima-bot

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - clima-bot

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - clima-bot

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - clima-bot

networks:
  clima-bot:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: