{
 "title": "Taxa de Requisições HTTP",
 "time": { "from": "2025-04-17T00:02:00.440Z", "to": "2025-04-17T03:30:31.916Z" },
 "panels": [
  {
   "title": "Distribuição da Latência (Histogram)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"clima_bot_api\"}[1m])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Requisições HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{job=\"clima_bot_api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo Médio de Resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"clima_bot_api\"}[1m]) / rate(http_request_duration_seconds_count{job=\"clima_bot_api\"}[1m])\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}